<#
.SYNOPSIS
    Decompiles the Bannerlord game assemblies into ./decompiled/ for reference,
    tracking each source DLL's SHA256 in a committed lock file so that a game
    update can be detected and only the changed assemblies re-decompiled.

.DESCRIPTION
    The decompiled/ tree is gitignored (it is derived, large, and TaleWorlds'
    copyrighted code). The lock file tools/bannerlord-assemblies.lock.json IS
    committed: after a game patch, run this script and `git diff` the lock file
    to see exactly which assemblies TaleWorlds touched.

.PARAMETER Scope
    Core (default) - single-player assemblies RBM actually patches, plus NavalDLC.
    Full           - every managed TaleWorlds/SandBox/StoryMode/NavalDLC/Multiplayer assembly.

.PARAMETER Force
    Re-decompile everything, ignoring the lock file.

.PARAMETER Check
    Do not decompile. Only report which assemblies differ from the lock file.
    Exit code 1 if anything is out of date (useful for a pre-build check).

.EXAMPLE
    .\tools\Decompile-Bannerlord.ps1
    .\tools\Decompile-Bannerlord.ps1 -Check
    .\tools\Decompile-Bannerlord.ps1 -Scope Full -Force
#>
[CmdletBinding()]
param(
    [ValidateSet('Core', 'Full')]
    [string]$Scope = 'Core',
    [switch]$Force,
    [switch]$Check
)

$ErrorActionPreference = 'Stop'

$repoRoot  = Split-Path -Parent $PSScriptRoot
$gameRoot  = Split-Path -Parent (Split-Path -Parent $repoRoot)   # ...\Mount & Blade II Bannerlord
$gameBin   = Join-Path $gameRoot 'bin\Win64_Shipping_Client'
$outRoot   = Join-Path $repoRoot 'decompiled'
$lockPath  = Join-Path $PSScriptRoot 'bannerlord-assemblies.lock.json'

$ilspy = Join-Path $env:USERPROFILE '.dotnet\tools\ilspycmd.exe'
if (-not (Test-Path $ilspy)) {
    $cmd = Get-Command ilspycmd -ErrorAction SilentlyContinue
    if ($null -eq $cmd) {
        throw "ilspycmd not found. Install it with: dotnet tool install -g ilspycmd"
    }
    $ilspy = $cmd.Source
}

if (-not (Test-Path $gameBin)) { throw "Game bin not found at $gameBin" }

# --- Which module bin folders hold managed assemblies -------------------------
$moduleBins = @()
foreach ($m in @('Native', 'SandBox', 'SandBoxCore', 'StoryMode', 'CustomBattle', 'Multiplayer', 'NavalDLC')) {
    $p = Join-Path $gameRoot "Modules\$m\bin\Win64_Shipping_Client"
    if (Test-Path $p) { $moduleBins += $p }
}

# --- Assembly selection -------------------------------------------------------
# Managed TaleWorlds code only. Native interop stubs and third-party redistributables
# (PhysX, Steamworks, Newtonsoft, ...) are excluded - nothing to learn from them.
$excludePatterns = @(
    'TaleWorlds.Native*',            # thin P/Invoke shims over the C++ engine
    'TaleWorlds.*.AutoGenerated*',   # codegen noise, hundreds of thousands of lines
    'TaleWorlds.Diamond*',           # online services backend
    'TaleWorlds.AchievementSystem*',
    'TaleWorlds.ActivitySystem*',
    'TaleWorlds.PlayerServices*',
    'TaleWorlds.Network*',
    'TaleWorlds.Starter*',
    'TaleWorlds.PSAI*',
    'TaleWorlds.BoxingLibrary*'
)

# Core scope: what RBM actually reads or patches.
$coreAssemblies = @(
    'TaleWorlds.CampaignSystem',
    'TaleWorlds.CampaignSystem.ViewModelCollection',
    'TaleWorlds.Core',
    'TaleWorlds.Core.ViewModelCollection',
    'TaleWorlds.Engine',
    'TaleWorlds.Engine.GauntletUI',
    'TaleWorlds.GauntletUI',
    'TaleWorlds.GauntletUI.Data',
    'TaleWorlds.GauntletUI.ExtraWidgets',
    'TaleWorlds.GauntletUI.PrefabSystem',
    'TaleWorlds.InputSystem',
    'TaleWorlds.Library',
    'TaleWorlds.LinQuick',
    'TaleWorlds.Localization',
    'TaleWorlds.MountAndBlade',
    'TaleWorlds.MountAndBlade.CustomBattle',
    'TaleWorlds.MountAndBlade.GauntletUI',
    'TaleWorlds.MountAndBlade.Platform.PC',
    'TaleWorlds.MountAndBlade.View',
    'TaleWorlds.MountAndBlade.ViewModelCollection',
    'TaleWorlds.ObjectSystem',
    'TaleWorlds.SaveSystem',
    'TaleWorlds.ScreenSystem',
    'TaleWorlds.ServiceDiscovery',
    'TaleWorlds.TwoDimension',
    'SandBox',
    'SandBox.GauntletUI',
    'SandBox.View',
    'SandBox.ViewModelCollection',
    'StoryMode',
    'StoryMode.GauntletUI',
    'StoryMode.View',
    'StoryMode.ViewModelCollection',
    'NavalDLC',
    'NavalDLC.CustomBattle',
    'NavalDLC.View',
    'NavalDLC.ViewModelCollection'
)

$searchDirs = @($gameBin) + $moduleBins
$candidates = @{}   # assembly name -> full path (first hit wins; game bin has priority)

foreach ($dir in $searchDirs) {
    foreach ($dll in Get-ChildItem -Path $dir -Filter *.dll -File) {
        $name = [System.IO.Path]::GetFileNameWithoutExtension($dll.Name)

        if ($Scope -eq 'Core') {
            if ($coreAssemblies -notcontains $name) { continue }
        }
        else {
            if ($name -notmatch '^(TaleWorlds|SandBox|StoryMode|NavalDLC)') { continue }
            $skip = $false
            foreach ($pat in $excludePatterns) { if ($name -like $pat) { $skip = $true; break } }
            if ($skip) { continue }
        }

        if (-not $candidates.ContainsKey($name)) { $candidates[$name] = $dll.FullName }
    }
}

if ($candidates.Count -eq 0) { throw "No assemblies matched scope '$Scope'." }

# --- Load the existing lock ---------------------------------------------------
$oldEntries = @{}
$oldGameVersion = ''
if ((Test-Path $lockPath) -and -not $Force) {
    $lock = Get-Content $lockPath -Raw | ConvertFrom-Json
    if ($null -ne $lock.gameVersion) { $oldGameVersion = $lock.gameVersion }
    foreach ($e in $lock.assemblies) { $oldEntries[$e.name] = $e }
}

# TaleWorlds stamps every assembly FileVersion 1.0.0.0, so the only honest
# version marker is the Native module manifest (e.g. "v1.3.13").
$gameVersion = 'unknown'
$nativeManifest = Join-Path $gameRoot 'Modules\Native\SubModule.xml'
if (Test-Path $nativeManifest) {
    $node = ([xml](Get-Content $nativeManifest -Raw)).Module.Version
    if ($node) { $gameVersion = $node.value }
}

# --- Diff ---------------------------------------------------------------------
$plan = @()
foreach ($name in ($candidates.Keys | Sort-Object)) {
    $path = $candidates[$name]
    $hash = (Get-FileHash -Path $path -Algorithm SHA256).Hash
    $outDir = Join-Path $outRoot $name

    $status = 'unchanged'
    if (-not $oldEntries.ContainsKey($name)) {
        $status = 'new'
    }
    elseif ($oldEntries[$name].sha256 -ne $hash) {
        $status = 'changed'
    }
    elseif (-not (Test-Path $outDir)) {
        $status = 'missing-output'
    }

    $plan += [pscustomobject]@{
        name    = $name
        path    = $path
        sha256  = $hash
        size    = (Get-Item $path).Length
        status  = $status
        outDir  = $outDir
    }
}

# Assemblies that were in the lock but no longer exist on disk.
$removed = @($oldEntries.Keys | Where-Object { -not $candidates.ContainsKey($_) })

$todo = @($plan | Where-Object { $_.status -ne 'unchanged' })

Write-Host ""
Write-Host "Game version : $gameVersion" -ForegroundColor Cyan
if ($oldGameVersion -and $oldGameVersion -ne $gameVersion) {
    Write-Host "Lock version : $oldGameVersion  <-- GAME WAS UPDATED" -ForegroundColor Yellow
}
Write-Host "Scope        : $Scope  ($($plan.Count) assemblies)" -ForegroundColor Cyan
Write-Host ""

if ($todo.Count -eq 0 -and $removed.Count -eq 0) {
    Write-Host "All decompiled output is up to date." -ForegroundColor Green
    if ($Check) { exit 0 }
}
else {
    foreach ($item in $todo) {
        $color = 'Yellow'
        if ($item.status -eq 'new') { $color = 'Green' }
        Write-Host ("  [{0,-14}] {1}" -f $item.status, $item.name) -ForegroundColor $color
    }
    foreach ($r in $removed) {
        Write-Host ("  [{0,-14}] {1}" -f 'removed', $r) -ForegroundColor DarkGray
    }
    Write-Host ""
}

if ($Check) {
    if ($todo.Count -gt 0 -or $removed.Count -gt 0) {
        Write-Host "Out of date. Run: .\tools\Decompile-Bannerlord.ps1" -ForegroundColor Yellow
        exit 1
    }
    exit 0
}

# --- Decompile ----------------------------------------------------------------
$refArgs = @()
foreach ($dir in $searchDirs) { $refArgs += @('-r', $dir) }

$failed = @()
$i = 0
foreach ($item in $todo) {
    $i++
    Write-Host ("[{0}/{1}] {2}" -f $i, $todo.Count, $item.name) -ForegroundColor Cyan

    if (Test-Path $item.outDir) { Remove-Item $item.outDir -Recurse -Force }
    New-Item -ItemType Directory -Path $item.outDir -Force | Out-Null

    $ilspyArgs = @('-p', '-o', $item.outDir) + $refArgs + @($item.path)
    # No 2>&1 here: in Windows PowerShell 5.1 redirecting a native exe's stderr
    # wraps each line in a NativeCommandError, which $ErrorActionPreference='Stop'
    # turns into a terminating error even on a successful (exit 0) run.
    & $ilspy @ilspyArgs | Out-Null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "    FAILED (exit $LASTEXITCODE)" -ForegroundColor Red
        $failed += $item.name
        $item.status = 'failed'
    }
}

# --- Write the lock -----------------------------------------------------------
# Only record assemblies that decompiled successfully, so a failure is retried
# on the next run rather than being silently baked in as up-to-date.
$entries = @()
foreach ($item in ($plan | Sort-Object name)) {
    if ($failed -contains $item.name) { continue }
    $entries += [pscustomobject]@{
        name    = $item.name
        source  = $item.path.Substring($gameRoot.Length).TrimStart('\')
        size    = $item.size
        sha256  = $item.sha256
    }
}

$lockObj = [pscustomobject]@{
    '$comment'  = 'SHA256 of each Bannerlord assembly last decompiled into ./decompiled/. Committed on purpose: after a game update, re-run tools/Decompile-Bannerlord.ps1 and diff this file to see which assemblies TaleWorlds changed. The decompiled sources themselves are gitignored.'
    gameVersion = $gameVersion
    scope       = $Scope
    generatedBy = (& $ilspy --version | Select-Object -First 1)
    assemblies  = $entries
}

$lockObj | ConvertTo-Json -Depth 5 | Out-File -FilePath $lockPath -Encoding utf8

Write-Host ""
if ($failed.Count -gt 0) {
    Write-Host "Done with $($failed.Count) failure(s): $($failed -join ', ')" -ForegroundColor Red
    exit 1
}
Write-Host "Done. Lock file updated: tools\bannerlord-assemblies.lock.json" -ForegroundColor Green
exit 0
